### ISSUE TITLE
FCO Item Saver interaction broken

### ISSUE THREAD

**Issue by kayplicated** [MaraRinn/ESO-MassDeconstructor#16]
I've enabled decon bound and set items in MassDecon, because i wanna decon stuff which is marked for decon in FCO but also bound and/or sets.
At the crafting station, the list of items in my decon window shows only the items which are marked for decon with FCO but when I hit the MassDecon button it starts to also pull in bound and/or set items which aren't marked for decon. MassDecon luckly doesn't decon those items but it stops with the message that the item is not allowed for decon instead of just skipping it and going to the next item in the list.
This happens with bound and set items which are marked with anything else but decon in FCO. I haven't tested it ornate yet though.

**Comment by kayplicated** [comment]
That issue might have been a general prob with saved variables by addons.
I've redid all markings in FCO and the issue seems to be solved.

I mark this bug as closed for now and reopen it if that issue turns up again.

**Comment by MaraRinn** [comment]
Phew! I'm glad that worked out okay! Thank you for taking the time to report the initial problem ^.^
